/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent_management;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Tanvir
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jTextField_French_Fries1 = new javax.swing.JTextField();
        jTextField_Sandwiches1 = new javax.swing.JTextField();
        jTextField_Pizza = new javax.swing.JTextField();
        jTextField_Burger1 = new javax.swing.JTextField();
        jTextField_Shawarma1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldChicken_Grilled1 = new javax.swing.JTextField();
        Chicken_Grilled1 = new javax.swing.JLabel();
        jCheckBox_Shawarma1 = new javax.swing.JLabel();
        jCheckBox_Sandwiches1 = new javax.swing.JLabel();
        jCheckBox_Burger1 = new javax.swing.JLabel();
        jCheckBox_French_Fries1 = new javax.swing.JLabel();
        jCheckBox_Pizza1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField_coffee = new javax.swing.JTextField();
        jTextField_Apple_Juice = new javax.swing.JTextField();
        jTextField_Tea = new javax.swing.JTextField();
        jTextField_Coca_Cola = new javax.swing.JTextField();
        jTextField_Sprite = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldWater = new javax.swing.JTextField();
        Water = new javax.swing.JLabel();
        jCheckBox_Sprite = new javax.swing.JLabel();
        jCheckBox_Apple_Juice = new javax.swing.JLabel();
        jCheckBox_Coca_Cola = new javax.swing.JLabel();
        jCheckBox_Ice_Cream = new javax.swing.JLabel();
        jCheckBox_Tea = new javax.swing.JLabel();
        jCheckBox_Coffee = new javax.swing.JLabel();
        jTextField_Ice_Cream = new javax.swing.JTextField();
        jCheckBox_Fanta = new javax.swing.JLabel();
        jTextField_fanta = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        j_cost_of_delivery = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcost_of_food = new javax.swing.JTextField();
        j_cost_of_drinks = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jText_tax = new javax.swing.JTextField();
        jText_total = new javax.swing.JTextField();
        jTxtSubTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton_Receipt = new javax.swing.JButton();
        jButton_reset = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jButton_total = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextReceipt = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(210, 77, 87));
        jTextField1.setFont(new java.awt.Font("Vivaldi", 3, 55)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("    Resturent Management System");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(108, 122, 137));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextField_French_Fries1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_French_Fries1.setText("      0");
        jTextField_French_Fries1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Sandwiches1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Sandwiches1.setText("      0 ");
        jTextField_Sandwiches1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField_Sandwiches1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Sandwiches1ActionPerformed(evt);
            }
        });

        jTextField_Pizza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Pizza.setText("      0");
        jTextField_Pizza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Burger1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Burger1.setText("      0");
        jTextField_Burger1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Shawarma1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Shawarma1.setText("      0");
        jTextField_Shawarma1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Food Item");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextFieldChicken_Grilled1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldChicken_Grilled1.setText("      0");
        jTextFieldChicken_Grilled1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextFieldChicken_Grilled1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldChicken_Grilled1ActionPerformed(evt);
            }
        });

        Chicken_Grilled1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Chicken_Grilled1.setText("Chicken Grilled");

        jCheckBox_Shawarma1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Shawarma1.setText("Shawarma");

        jCheckBox_Sandwiches1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Sandwiches1.setText("Sandwiches");

        jCheckBox_Burger1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Burger1.setText("Burger");

        jCheckBox_French_Fries1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_French_Fries1.setText("French Fries");

        jCheckBox_Pizza1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Pizza1.setText("Pizza");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(Chicken_Grilled1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jTextFieldChicken_Grilled1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jCheckBox_French_Fries1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_French_Fries1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Shawarma1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Shawarma1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Sandwiches1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Sandwiches1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Pizza1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Burger1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Burger1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldChicken_Grilled1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chicken_Grilled1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Burger1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Burger1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Shawarma1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Shawarma1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Sandwiches1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Sandwiches1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_Pizza1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jTextField_French_Fries1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox_French_Fries1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        jPanel9.setBackground(new java.awt.Color(108, 122, 137));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextField_coffee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_coffee.setText("      0");
        jTextField_coffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Apple_Juice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Apple_Juice.setText("      0");
        jTextField_Apple_Juice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField_Apple_Juice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Apple_JuiceActionPerformed(evt);
            }
        });

        jTextField_Tea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Tea.setText("      0");
        jTextField_Tea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Coca_Cola.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Coca_Cola.setText("      0");
        jTextField_Coca_Cola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Sprite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Sprite.setText("      0");
        jTextField_Sprite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Drinks Item");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextFieldWater.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldWater.setText("      0");
        jTextFieldWater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Water.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Water.setText("Water");

        jCheckBox_Sprite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Sprite.setText("Sprite");

        jCheckBox_Apple_Juice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Apple_Juice.setText("Apple_Juice");

        jCheckBox_Coca_Cola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Coca_Cola.setText("Coca_Cola");

        jCheckBox_Ice_Cream.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Ice_Cream.setText("Ice_Cream");

        jCheckBox_Tea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Tea.setText("Tea");

        jCheckBox_Coffee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Coffee.setText("Coffee");

        jTextField_Ice_Cream.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Ice_Cream.setText("      0");
        jTextField_Ice_Cream.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCheckBox_Fanta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Fanta.setText("Fanta");

        jTextField_fanta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_fanta.setText("      0");
        jTextField_fanta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(Water)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldWater, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Coffee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Sprite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Apple_Juice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jTextField_Apple_Juice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Tea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Coca_Cola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Coca_Cola, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Fanta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Ice_Cream)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Ice_Cream, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWater, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Water, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Coca_Cola, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Coca_Cola, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Apple_Juice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Apple_Juice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Ice_Cream, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Ice_Cream, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel2.setBackground(new java.awt.Color(171, 183, 183));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cost of Drinks");

        j_cost_of_delivery.setEditable(false);
        j_cost_of_delivery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j_cost_of_delivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j_cost_of_delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_cost_of_deliveryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cost of Delivery");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost of food");

        jcost_of_food.setEditable(false);
        jcost_of_food.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcost_of_food.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcost_of_food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcost_of_foodActionPerformed(evt);
            }
        });

        j_cost_of_drinks.setEditable(false);
        j_cost_of_drinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j_cost_of_drinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j_cost_of_drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_cost_of_drinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcost_of_food, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(j_cost_of_drinks)
                    .addComponent(j_cost_of_delivery))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(j_cost_of_drinks, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcost_of_food, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(j_cost_of_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel5.setBackground(new java.awt.Color(0, 177, 106));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Sub Total");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tax:");

        jText_tax.setEditable(false);
        jText_tax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText_total.setEditable(false);
        jText_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtSubTotal.setEditable(false);
        jTxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSubTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jText_total, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jText_tax)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(27, 163, 156));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton_Receipt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Receipt.setText("Receipt");
        jButton_Receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ReceiptMouseClicked(evt);
            }
        });
        jButton_Receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReceiptActionPerformed(evt);
            }
        });

        jButton_reset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_reset.setText("Reset");
        jButton_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_resetMouseClicked(evt);
            }
        });
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Exit.setText("Exit");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jButton_total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_total.setText("Total");
        jButton_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_total)
                .addGap(35, 35, 35)
                .addComponent(jButton_Receipt)
                .addGap(28, 28, 28)
                .addComponent(jButton_reset)
                .addGap(28, 28, 28)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(334, 334, 334))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_total)
                    .addComponent(jButton_Receipt)
                    .addComponent(jButton_reset)
                    .addComponent(jButton_Exit))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextReceipt.setColumns(20);
        jTextReceipt.setRows(5);
        jScrollPane1.setViewportView(jTextReceipt);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField2.setText("Receipt");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField_Sandwiches1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Sandwiches1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Sandwiches1ActionPerformed

    private void jTextField_Apple_JuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Apple_JuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Apple_JuiceActionPerformed

    private void j_cost_of_deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_cost_of_deliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_cost_of_deliveryActionPerformed

    private void jcost_of_foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcost_of_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcost_of_foodActionPerformed

    private void j_cost_of_drinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_cost_of_drinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_cost_of_drinksActionPerformed

    private void jTxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSubTotalActionPerformed

    private void jButton_ReceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ReceiptMouseClicked

    }//GEN-LAST:event_jButton_ReceiptMouseClicked

    private void jButton_ReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReceiptActionPerformed

        //===================================================================
        int refs = 1325 +(int)(Math.random()*4238);
        //===================================================================
         Calendar timer = Calendar.getInstance();
         timer.getTime();
        SimpleDateFormat tTime =new SimpleDateFormat("HH:MM:SS");
        tTime.format(timer.getTime());
         SimpleDateFormat Tdate =new SimpleDateFormat("dd-MM-yyyy");
        Tdate.format(timer.getTime());
        jTextReceipt.append(" Resturent Management System\n\n" + 
                "Reference:\t\t"+ refs +
                
                "\n===================================\n" +
                "Food:\t\t" + jcost_of_food.getText() + "\n\n" +
                "Drinks:\t\t" +  j_cost_of_drinks.getText()+"\n\n"+
                "Delivery cost\t\t"+ j_cost_of_delivery.getText()+"\n\n"+
                "======================================"+"\n\n"+
                "Tax:\t\t"+jText_tax.getText()+"\n\n"+
                "Sub Total:\t\t"+jTxtSubTotal.getText()+"\n\n"+
                "Total:\t\t"+ jText_total.getText()+"\n\n"+
                "======================================="+
                "\nDate:"+Tdate.format(timer.getTime())+
                "\tTime:" + tTime.format(timer.getTime())+
                "\n\n\tThank you"
                );

    }//GEN-LAST:event_jButton_ReceiptActionPerformed

    private void jButton_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_resetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_resetMouseClicked

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        j_cost_of_delivery.setText(null);
        j_cost_of_drinks.setText(null);
        jcost_of_food.setText(null);
        JTextField cleartext =null;
        for (Component c:jPanel9.getComponents() ){
            if(c.getClass().toString().contains("JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        for (Component c:jPanel5.getComponents() ){
            if(c.getClass().toString().contains("JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
        for (Component c:jPanel10.getComponents() ){
            if(c.getClass().toString().contains("JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_totalActionPerformed
        food_item_child ItemCost= new food_item_child();

        double iTax,iSubTotal,iTotal;
try{
        ItemCost.Burger=Double.parseDouble(jTextField_Burger1.getText()) * ItemCost.pBurger;
}
catch(Exception e){
    System.out.println("You can't do this");
}
        
try{
        ItemCost.Chicken_Grilled=Double.parseDouble(jTextFieldChicken_Grilled1.getText()) * ItemCost.pChicken_Grilled;
        ItemCost.French_Fries=Double.parseDouble(jTextField_French_Fries1.getText()) * ItemCost.pFrench_Fries;
        ItemCost.Pizza=Double.parseDouble(jTextField_Pizza.getText()) * ItemCost.pPizza;
        ItemCost.Shawarma=Double.parseDouble(jTextField_Shawarma1.getText()) * ItemCost.pShawarma;
        ItemCost.Sandwiches=Double.parseDouble(jTextField_Sandwiches1.getText()) * ItemCost.pSandwiches;
        ItemCost.Apple_Juice=Double.parseDouble(jTextField_Apple_Juice.getText()) * ItemCost.pApple_Juice;
        ItemCost.Coca_Cola=Double.parseDouble(jTextField_Coca_Cola.getText()) * ItemCost.pCoca_Cola;
        ItemCost.Coffee=Double.parseDouble(jTextField_coffee.getText()) * ItemCost.pCoffee;
        ItemCost.Fanta=Double.parseDouble(jTextField_fanta.getText()) * ItemCost.pFanta;
        ItemCost.Tea=Double.parseDouble(jTextField_Tea.getText()) * ItemCost.pTea;
        ItemCost.Water=Double.parseDouble(jTextFieldWater.getText()) * ItemCost.pWater;
        ItemCost.Ice_Cream=Double.parseDouble(jTextField_Ice_Cream.getText()) * ItemCost.pIce_Cream;
        ItemCost.Sprite=Double.parseDouble(jTextField_Sprite.getText()) * ItemCost.pSprite;
}
        catch(Exception e){
    System.out.println("You can't do this");
}

        iSubTotal=ItemCost.getAmount();
        iTax=ItemCost.cfindTax();
        iTotal=iSubTotal + iTax;

        String SubTotal=String.format("BDT %.2f",iSubTotal);
        jTxtSubTotal.setText(SubTotal);

        String Tax=String.format("BDT %.2f",iTax);
        jText_tax.setText(Tax);

        String Total=String.format("BDT %.2f",iTotal);
        jText_total.setText(Total);
        
        String  Food=String.format("BDT %.2f",ItemCost.Food);
        jcost_of_food.setText( Food);
        String  Drink=String.format("BDT %.2f",ItemCost.Drink);
        j_cost_of_drinks.setText( Drink);

        String  Cost_of_deleviry=String.format("BDT %.2f",ItemCost.cost_of_delivery);
        j_cost_of_delivery.setText( Cost_of_deleviry);


         try
           {
               Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=resturent;user=dipu;password=tanvir1996;";
            
            Connection connection ;
            PreparedStatement pst;
             String query;
            connection = DriverManager.getConnection(connectionUrl);
             query="insert into daily_total(cost)values(?)";
              pst=connection.prepareStatement(query);
              pst.setString(1, Total);
            
              
              pst.executeUpdate();
              
              
              
           }
           
           catch(ClassNotFoundException | SQLException e)
                   {
                      JOptionPane.showMessageDialog(null,e); 
                   }
         
         

    }//GEN-LAST:event_jButton_totalActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextFieldChicken_Grilled1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldChicken_Grilled1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldChicken_Grilled1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chicken_Grilled1;
    private javax.swing.JLabel Water;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_Receipt;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_total;
    private javax.swing.JLabel jCheckBox_Apple_Juice;
    private javax.swing.JLabel jCheckBox_Burger1;
    private javax.swing.JLabel jCheckBox_Coca_Cola;
    private javax.swing.JLabel jCheckBox_Coffee;
    private javax.swing.JLabel jCheckBox_Fanta;
    private javax.swing.JLabel jCheckBox_French_Fries1;
    private javax.swing.JLabel jCheckBox_Ice_Cream;
    private javax.swing.JLabel jCheckBox_Pizza1;
    private javax.swing.JLabel jCheckBox_Sandwiches1;
    private javax.swing.JLabel jCheckBox_Shawarma1;
    private javax.swing.JLabel jCheckBox_Sprite;
    private javax.swing.JLabel jCheckBox_Tea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldChicken_Grilled1;
    private javax.swing.JTextField jTextFieldWater;
    private javax.swing.JTextField jTextField_Apple_Juice;
    private javax.swing.JTextField jTextField_Burger1;
    private javax.swing.JTextField jTextField_Coca_Cola;
    private javax.swing.JTextField jTextField_French_Fries1;
    private javax.swing.JTextField jTextField_Ice_Cream;
    private javax.swing.JTextField jTextField_Pizza;
    private javax.swing.JTextField jTextField_Sandwiches1;
    private javax.swing.JTextField jTextField_Shawarma1;
    private javax.swing.JTextField jTextField_Sprite;
    private javax.swing.JTextField jTextField_Tea;
    private javax.swing.JTextField jTextField_coffee;
    private javax.swing.JTextField jTextField_fanta;
    private javax.swing.JTextArea jTextReceipt;
    private javax.swing.JTextField jText_tax;
    private javax.swing.JTextField jText_total;
    private javax.swing.JTextField jTxtSubTotal;
    private javax.swing.JTextField j_cost_of_delivery;
    private javax.swing.JTextField j_cost_of_drinks;
    private javax.swing.JTextField jcost_of_food;
    // End of variables declaration//GEN-END:variables
}
