/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package resturent_management;
import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
public class Manager_option extends javax.swing.JFrame {

    double firstnum;
    double secondnum;
    double result;
    String operations;
    public Manager_option() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        j_cost_of_delivery = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcost_of_food = new javax.swing.JTextField();
        j_cost_of_drinks = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jTabbed_receipt = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        JtxtDisplay = new javax.swing.JTextField();
        jButtonn4 = new javax.swing.JButton();
        jButtonn7 = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonn1 = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonn2 = new javax.swing.JButton();
        jButtonn5 = new javax.swing.JButton();
        jButtonn8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonn3 = new javax.swing.JButton();
        jButtonn6 = new javax.swing.JButton();
        jButtonn9 = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButton_multi = new javax.swing.JButton();
        jButton_milus = new javax.swing.JButton();
        jButton_plus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonequl = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jText_tax = new javax.swing.JTextField();
        jText_total = new javax.swing.JTextField();
        jTxtSubTotal = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jTextField_coffee = new javax.swing.JTextField();
        jTextField_Apple_Juice = new javax.swing.JTextField();
        jTextField_Tea = new javax.swing.JTextField();
        jTextField_Coca_Cola = new javax.swing.JTextField();
        jTextField_Sprite = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldWater = new javax.swing.JTextField();
        Water = new javax.swing.JLabel();
        jCheckBox_Sprite = new javax.swing.JLabel();
        jCheckBox_Apple_Juice = new javax.swing.JLabel();
        jCheckBox_Coca_Cola = new javax.swing.JLabel();
        jCheckBox_Ice_Cream = new javax.swing.JLabel();
        jCheckBox_Tea = new javax.swing.JLabel();
        jCheckBox_Coffee = new javax.swing.JLabel();
        jTextField_Ice_Cream = new javax.swing.JTextField();
        jCheckBox_Fanta = new javax.swing.JLabel();
        jTextField_fanta = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton_reset = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jButton_total = new javax.swing.JButton();
        jPanelfood = new javax.swing.JPanel();
        jTextField_French_Fries1 = new javax.swing.JTextField();
        jTextField_Sandwiches1 = new javax.swing.JTextField();
        jTextField_Pizza = new javax.swing.JTextField();
        jTextField_Burger1 = new javax.swing.JTextField();
        jTextField_Shawarma1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldChicken_Grilled1 = new javax.swing.JTextField();
        Chicken_Grilled1 = new javax.swing.JLabel();
        jCheckBox_Shawarma1 = new javax.swing.JLabel();
        jCheckBox_Sandwiches1 = new javax.swing.JLabel();
        jCheckBox_Burger1 = new javax.swing.JLabel();
        jCheckBox_French_Fries1 = new javax.swing.JLabel();
        jCheckBox_Pizza1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(171, 183, 183));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cost of Drinks");

        j_cost_of_delivery.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j_cost_of_delivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j_cost_of_delivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_cost_of_deliveryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cost of Delivery");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost of food");

        jcost_of_food.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcost_of_food.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jcost_of_food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcost_of_foodActionPerformed(evt);
            }
        });

        j_cost_of_drinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j_cost_of_drinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j_cost_of_drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_cost_of_drinksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcost_of_food, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(j_cost_of_drinks)
                    .addComponent(j_cost_of_delivery))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(j_cost_of_drinks, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcost_of_food, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(j_cost_of_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 110, 260, -1));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        JtxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JtxtDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        JtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtDisplayActionPerformed(evt);
            }
        });

        jButtonn4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn4.setText("4");
        jButtonn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn4ActionPerformed(evt);
            }
        });

        jButtonn7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn7.setText("7");
        jButtonn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn7ActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn1.setText("1");
        jButtonn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn1ActionPerformed(evt);
            }
        });

        jButtonC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn2.setText("2");
        jButtonn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn2ActionPerformed(evt);
            }
        });

        jButtonn5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn5.setText("5");
        jButtonn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn5ActionPerformed(evt);
            }
        });

        jButtonn8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn8.setText("8");
        jButtonn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("Del");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonn3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn3.setText("3");
        jButtonn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn3ActionPerformed(evt);
            }
        });

        jButtonn6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn6.setText("6");
        jButtonn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn6ActionPerformed(evt);
            }
        });

        jButtonn9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonn9.setText("9");
        jButtonn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonn9ActionPerformed(evt);
            }
        });

        jButtonDiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDiv.setText("/");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jButton_multi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_multi.setText("*");
        jButton_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_multiActionPerformed(evt);
            }
        });

        jButton_milus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_milus.setText("-");
        jButton_milus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_milusActionPerformed(evt);
            }
        });

        jButton_plus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_plus.setText("+");
        jButton_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_plusActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText(".");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonequl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonequl.setText("=");
        jButtonequl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonequlActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Tahoma", 1, 8)); // NOI18N
        jButton20.setText("+/-");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JtxtDisplay)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonn7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonn2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonn5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonn8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(jButtonn9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jButtonn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButtonn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_milus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonequl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jButton_plus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_milus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonn6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonn3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButtonn7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonn4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonn8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonn9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonn2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonequl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbed_receipt.addTab("Calculator", jPanel7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbed_receipt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbed_receipt, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, 320, 460));

        jPanel5.setBackground(new java.awt.Color(0, 177, 106));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Sub Total");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Tax:");

        jText_tax.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jText_total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jText_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSubTotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jText_total, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jText_tax)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_tax, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_total, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 260, 190));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(210, 77, 87));
        jTextField1.setFont(new java.awt.Font("Vivaldi", 3, 55)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("    Resturent Management System");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 0, 1030, 98));

        jPanel9.setBackground(new java.awt.Color(108, 122, 137));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextField_coffee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_coffee.setText("      0");
        jTextField_coffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Apple_Juice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Apple_Juice.setText("      0");
        jTextField_Apple_Juice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField_Apple_Juice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Apple_JuiceActionPerformed(evt);
            }
        });

        jTextField_Tea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Tea.setText("      0");
        jTextField_Tea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Coca_Cola.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Coca_Cola.setText("      0");
        jTextField_Coca_Cola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Sprite.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Sprite.setText("      0");
        jTextField_Sprite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Drinks Item");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextFieldWater.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldWater.setText("      0");
        jTextFieldWater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextFieldWater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWaterActionPerformed(evt);
            }
        });

        Water.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Water.setText("Water");

        jCheckBox_Sprite.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Sprite.setText("Sprite");

        jCheckBox_Apple_Juice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Apple_Juice.setText("Apple_Juice");

        jCheckBox_Coca_Cola.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Coca_Cola.setText("Coca_Cola");

        jCheckBox_Ice_Cream.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Ice_Cream.setText("Ice_Cream");

        jCheckBox_Tea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Tea.setText("Tea");

        jCheckBox_Coffee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Coffee.setText("Coffee");

        jTextField_Ice_Cream.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Ice_Cream.setText("      0");
        jTextField_Ice_Cream.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCheckBox_Fanta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Fanta.setText("Fanta");

        jTextField_fanta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_fanta.setText("      0");
        jTextField_fanta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(Water)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jTextFieldWater, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Coffee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Sprite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Apple_Juice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Apple_Juice, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Tea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Coca_Cola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Coca_Cola, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Fanta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jCheckBox_Ice_Cream)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Ice_Cream, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWater, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Water, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Coca_Cola, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Coca_Cola, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Apple_Juice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Apple_Juice, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Tea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Coffee, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Ice_Cream, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Ice_Cream, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_fanta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 210, 360));

        jPanel4.setBackground(new java.awt.Color(27, 163, 156));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton_reset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_reset.setText("Reset");
        jButton_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_resetMouseClicked(evt);
            }
        });
        jButton_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_resetActionPerformed(evt);
            }
        });

        jButton_Exit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_Exit.setText("Exit");
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        jButton_total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton_total.setText("Total");
        jButton_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_totalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton_total)
                .addGap(94, 94, 94)
                .addComponent(jButton_reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_total)
                    .addComponent(jButton_reset)
                    .addComponent(jButton_Exit))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 700, 90));

        jPanelfood.setBackground(new java.awt.Color(108, 122, 137));
        jPanelfood.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextField_French_Fries1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_French_Fries1.setText("      0");
        jTextField_French_Fries1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Sandwiches1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Sandwiches1.setText("      0 ");
        jTextField_Sandwiches1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField_Sandwiches1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Sandwiches1ActionPerformed(evt);
            }
        });

        jTextField_Pizza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Pizza.setText("      0");
        jTextField_Pizza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Burger1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Burger1.setText("      0");
        jTextField_Burger1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextField_Shawarma1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField_Shawarma1.setText("      0");
        jTextField_Shawarma1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Food Item");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTextFieldChicken_Grilled1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextFieldChicken_Grilled1.setText("      0");
        jTextFieldChicken_Grilled1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Chicken_Grilled1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Chicken_Grilled1.setText("Chicken Grilled");

        jCheckBox_Shawarma1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Shawarma1.setText("Shawarma");

        jCheckBox_Sandwiches1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Sandwiches1.setText("Sandwiches");

        jCheckBox_Burger1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Burger1.setText("Burger");

        jCheckBox_French_Fries1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_French_Fries1.setText("French Fries");

        jCheckBox_Pizza1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox_Pizza1.setText("Pizza");

        javax.swing.GroupLayout jPanelfoodLayout = new javax.swing.GroupLayout(jPanelfood);
        jPanelfood.setLayout(jPanelfoodLayout);
        jPanelfoodLayout.setHorizontalGroup(
            jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfoodLayout.createSequentialGroup()
                .addGroup(jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfoodLayout.createSequentialGroup()
                        .addComponent(Chicken_Grilled1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jTextFieldChicken_Grilled1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfoodLayout.createSequentialGroup()
                        .addComponent(jCheckBox_French_Fries1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_French_Fries1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfoodLayout.createSequentialGroup()
                        .addComponent(jCheckBox_Shawarma1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Shawarma1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfoodLayout.createSequentialGroup()
                        .addComponent(jCheckBox_Sandwiches1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Sandwiches1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfoodLayout.createSequentialGroup()
                        .addComponent(jCheckBox_Pizza1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfoodLayout.createSequentialGroup()
                        .addComponent(jCheckBox_Burger1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_Burger1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelfoodLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanelfoodLayout.setVerticalGroup(
            jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelfoodLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldChicken_Grilled1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Chicken_Grilled1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Burger1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Burger1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Shawarma1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Shawarma1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Sandwiches1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_Sandwiches1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelfoodLayout.createSequentialGroup()
                        .addGroup(jPanelfoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Pizza, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox_Pizza1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jTextField_French_Fries1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox_French_Fries1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        getContentPane().add(jPanelfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void j_cost_of_deliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_cost_of_deliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_cost_of_deliveryActionPerformed

    private void jcost_of_foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcost_of_foodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcost_of_foodActionPerformed

    private void jTextField_Apple_JuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Apple_JuiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Apple_JuiceActionPerformed

    private void jTxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSubTotalActionPerformed

    private void jButton_resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_resetMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_resetMouseClicked

    private void jButton_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_resetActionPerformed
        j_cost_of_delivery.setText(null);
        j_cost_of_drinks.setText(null);
        jcost_of_food.setText(null);
        JTextField cleartext =null;
        for (Component c:jPanel9.getComponents() ){
            if(c.getClass().toString().contains("JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        for (Component c:jPanel5.getComponents() ){
            if(c.getClass().toString().contains("JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText(" ");
            }
        }
        for (Component c:jPanelfood.getComponents() ){
            if(c.getClass().toString().contains("JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }

    }//GEN-LAST:event_jButton_resetActionPerformed

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_totalActionPerformed
        food_item_child ItemCost= new food_item_child();

        double iTax,iSubTotal,iTotal;
try{
        ItemCost.Burger=Double.parseDouble(jTextField_Burger1.getText()) * ItemCost.pBurger;
        ItemCost.Chicken_Grilled=Double.parseDouble(jTextFieldChicken_Grilled1.getText()) * ItemCost.pChicken_Grilled;
        ItemCost.French_Fries=Double.parseDouble(jTextField_French_Fries1.getText()) * ItemCost.pFrench_Fries;
        ItemCost.Pizza=Double.parseDouble(jTextField_Pizza.getText()) * ItemCost.pPizza;
        ItemCost.Shawarma=Double.parseDouble(jTextField_Shawarma1.getText()) * ItemCost.pShawarma;
        ItemCost.Sandwiches=Double.parseDouble(jTextField_Sandwiches1.getText()) * ItemCost.pSandwiches;

        
        ItemCost.Apple_Juice=Double.parseDouble(jTextField_Apple_Juice.getText()) * ItemCost.pApple_Juice;
        ItemCost.Coca_Cola=Double.parseDouble(jTextField_Coca_Cola.getText()) * ItemCost.pCoca_Cola;
        ItemCost.Coffee=Double.parseDouble(jTextField_coffee.getText()) * ItemCost.pCoffee;
        ItemCost.Fanta=Double.parseDouble(jTextField_fanta.getText()) * ItemCost.pFanta;
        ItemCost.Tea=Double.parseDouble(jTextField_Tea.getText()) * ItemCost.pTea;
        ItemCost.Water=Double.parseDouble(jTextFieldWater.getText()) * ItemCost.pWater;
        ItemCost.Ice_Cream=Double.parseDouble(jTextField_Ice_Cream.getText()) * ItemCost.pIce_Cream;
        ItemCost.Sprite=Double.parseDouble(jTextField_Sprite.getText()) * ItemCost.pSprite;
}
catch(Exception e){
    System.out.println("You can't do it");
}
        iSubTotal=ItemCost.getAmount();
        iTax=ItemCost.cfindTax();
        iTotal=iSubTotal + iTax;

        String SubTotal=String.format("BDT %.2f",iSubTotal);
        jTxtSubTotal.setText(SubTotal);

        String Tax=String.format("BDT %.2f",iTax);
        jText_tax.setText(Tax);

        String Total=String.format("BDT %.2f",iTotal);
        jText_total.setText(Total);
        
        String  Food=String.format("BDT %.2f",ItemCost.Food);
        jcost_of_food.setText( Food);
        String  Drink=String.format("BDT %.2f",ItemCost.Drink);
        j_cost_of_drinks.setText( Drink);
        
        String  Cost_of_deleviry=String.format("BDT %.2f",ItemCost.cost_of_delivery);
        j_cost_of_delivery.setText( Cost_of_deleviry);
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton_totalActionPerformed

    private void jTextField_Sandwiches1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Sandwiches1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Sandwiches1ActionPerformed

    private void j_cost_of_drinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_cost_of_drinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_cost_of_drinksActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        double ops=Double.parseDouble(String.valueOf(JtxtDisplay.getText()));
        ops = ops * (-1);
        JtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButtonequlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonequlActionPerformed
        String answer;
        secondnum = Double.parseDouble(JtxtDisplay.getText());
        if(operations =="+")
        {
            result = firstnum + secondnum;
            answer=String.format("%.2f",result);
            JtxtDisplay.setText(answer);
        }
        else if(operations =="-")
        {
            result = firstnum - secondnum;
            answer=String.format("%.2f",result);
            JtxtDisplay.setText(answer);
        }
        else if(operations =="*")
        {
            result = firstnum * secondnum;
            answer=String.format("%.2f",result);
            JtxtDisplay.setText(answer);
        }
        else if(operations =="/")
        {
            result = firstnum / secondnum;
            answer=String.format("%.2f",result);
            JtxtDisplay.setText(answer);
        }
        else if(operations =="%")
        {
            result = firstnum % secondnum;
            answer=String.format("%.2f",result);
            JtxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jButtonequlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JtxtDisplay.setText(JtxtDisplay.getText()+ jButton1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_plusActionPerformed
        firstnum=Double.parseDouble(JtxtDisplay.getText());
        JtxtDisplay.setText("");
        operations="+";
    }//GEN-LAST:event_jButton_plusActionPerformed

    private void jButton_milusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_milusActionPerformed
        firstnum=Double.parseDouble(JtxtDisplay.getText());
        JtxtDisplay.setText("");
        operations="-";
    }//GEN-LAST:event_jButton_milusActionPerformed

    private void jButton_multiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_multiActionPerformed
        firstnum=Double.parseDouble(JtxtDisplay.getText());
        JtxtDisplay.setText("");
        operations="*";
    }//GEN-LAST:event_jButton_multiActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        firstnum=Double.parseDouble(JtxtDisplay.getText());
        JtxtDisplay.setText("");
        operations="/";
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButtonn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn9ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn9.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn9ActionPerformed

    private void jButtonn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn6ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn6.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn6ActionPerformed

    private void jButtonn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn3ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn3.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String backspace =null;
        if(JtxtDisplay.getText().length()>0){
            StringBuilder strB= new StringBuilder(JtxtDisplay.getText());
            strB.deleteCharAt(JtxtDisplay.getText().length()-1);
            backspace=strB.toString();
            JtxtDisplay.setText(backspace);

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn8ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn8.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn8ActionPerformed

    private void jButtonn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn5ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn5.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn5ActionPerformed

    private void jButtonn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn2ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn2.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn2ActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        JtxtDisplay.setText(null);
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn1ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn1.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn1ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButton0.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn7ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn7.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn7ActionPerformed

    private void jButtonn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonn4ActionPerformed
        String Enternumber = JtxtDisplay.getText()+jButtonn4.getText();
        JtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonn4ActionPerformed

    private void JtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtxtDisplayActionPerformed

    private void jTextFieldWaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWaterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWaterActionPerformed

    
    public static void main(String args[])  {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Chicken_Grilled1;
    private javax.swing.JTextField JtxtDisplay;
    private javax.swing.JLabel Water;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_milus;
    private javax.swing.JButton jButton_multi;
    private javax.swing.JButton jButton_plus;
    private javax.swing.JButton jButton_reset;
    private javax.swing.JButton jButton_total;
    private javax.swing.JButton jButtonequl;
    private javax.swing.JButton jButtonn1;
    private javax.swing.JButton jButtonn2;
    private javax.swing.JButton jButtonn3;
    private javax.swing.JButton jButtonn4;
    private javax.swing.JButton jButtonn5;
    private javax.swing.JButton jButtonn6;
    private javax.swing.JButton jButtonn7;
    private javax.swing.JButton jButtonn8;
    private javax.swing.JButton jButtonn9;
    private javax.swing.JLabel jCheckBox_Apple_Juice;
    private javax.swing.JLabel jCheckBox_Burger1;
    private javax.swing.JLabel jCheckBox_Coca_Cola;
    private javax.swing.JLabel jCheckBox_Coffee;
    private javax.swing.JLabel jCheckBox_Fanta;
    private javax.swing.JLabel jCheckBox_French_Fries1;
    private javax.swing.JLabel jCheckBox_Ice_Cream;
    private javax.swing.JLabel jCheckBox_Pizza1;
    private javax.swing.JLabel jCheckBox_Sandwiches1;
    private javax.swing.JLabel jCheckBox_Shawarma1;
    private javax.swing.JLabel jCheckBox_Sprite;
    private javax.swing.JLabel jCheckBox_Tea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelfood;
    private javax.swing.JTabbedPane jTabbed_receipt;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldChicken_Grilled1;
    private javax.swing.JTextField jTextFieldWater;
    private javax.swing.JTextField jTextField_Apple_Juice;
    private javax.swing.JTextField jTextField_Burger1;
    private javax.swing.JTextField jTextField_Coca_Cola;
    private javax.swing.JTextField jTextField_French_Fries1;
    private javax.swing.JTextField jTextField_Ice_Cream;
    private javax.swing.JTextField jTextField_Pizza;
    private javax.swing.JTextField jTextField_Sandwiches1;
    private javax.swing.JTextField jTextField_Shawarma1;
    private javax.swing.JTextField jTextField_Sprite;
    private javax.swing.JTextField jTextField_Tea;
    private javax.swing.JTextField jTextField_coffee;
    private javax.swing.JTextField jTextField_fanta;
    private javax.swing.JTextField jText_tax;
    private javax.swing.JTextField jText_total;
    private javax.swing.JTextField jTxtSubTotal;
    private javax.swing.JTextField j_cost_of_delivery;
    private javax.swing.JTextField j_cost_of_drinks;
    private javax.swing.JTextField jcost_of_food;
    // End of variables declaration//GEN-END:variables
}
